### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by aefox** [townsfolk/gradle-templates#25]
I'm asking because I'm having a project which uses this and we're having issues when we tried to use this with gradle 3.1. I'm willing to fix that but I need to know if anyone will review/merge/release it.

**Comment by cjstehno** [comment]
I would say yes. I think the original author would be amenable to updates; however, I would recommend using lazybones instead.

**Comment by cjstehno** [comment]
Sorry. I meant "no". I thought you asked if it was dead.
